import type { Metadata } from "next";
import { Arvo, Bitcount_Single, Delius, Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: "500",
});

const arvo = Arvo({
  variable: "--font-arvo",
  subsets: ["latin"],
  weight: "400",
});

const bitcountSingle = Bitcount_Single({
  variable: "--font-bitcount-single",
  subsets: ["latin"],
  weight: "600",
});

const delius = Delius({
  variable: "--font-delius",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "benjoe.dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${arvo.variable} ${bitcountSingle.variable} ${delius.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
